// <auto-generated />
namespace FUMETTERIA_CAP2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addispreferito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addispreferito));
        
        string IMigrationMetadata.Id
        {
            get { return "202311031443366_addispreferito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
